---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  serviceName: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
      - name: linkwarden
        image: ghcr.io/linkwarden/linkwarden:latest
        envFrom:
        - configMapRef:
            name: linkwarden-config
        - secretRef:
            name: linkwarden-secrets
        ports:
          - containerPort: 3000
        volumeMounts:
        - name: linkwarden-data
          mountPath: /data/data
  volumeClaimTemplates:
  - metadata:
      name: linkwarden-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkwarden-postgres
spec:
  selector:
    matchLabels:
      app: linkwarden-postgres
  serviceName: linkwarden-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: linkwarden-postgres
    spec:
      containers:
      - name: linkwarden-postgres
        image: postgres:latest
        envFrom:
        - secretRef:
            name: linkwarden-postgres-secrets
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden-postgres
spec:
  type: ClusterIP
  selector:
    app: linkwarden-postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
spec:
  type: ClusterIP
  selector:
    app: linkwarden
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkwarden-config
  labels:
    app: linkwarden
data:
  NEXTAUTH_URL: http://localhost:3000
  PAGINATION_TAKE_COUNT: '20'
  STORAGE_FOLDER: /data
  AUTOSCROLL_TIMEOUT: '30'
  NEXT_PUBLIC_DISABLE_REGISTRATION: 'false'
  NEXT_PUBLIC_EMAIL_PROVIDER: ''
  EMAIL_FROM: ''
  EMAIL_SERVER: ''

---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-postgres-secrets
type: Opaque
data:
  POSTGRES_DB: linkwarden
  POSTGRES_USER: linkwarden
  POSTGRES_PASSWORD: password

---
apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
type: Opaque
data:
  NEXTAUTH_SECRET: very_sensitive_secret
  DATABASE_URL: postgresql://user:password@localhost:5432/linkwarden
  POSTGRES_PASSWORD: password

