---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: longhorn-ui
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: web
  type: LoadBalancer
